project:
  type: website
  output-dir: docs # Cambiar de _site a docs
 
website:
  title: "Machine Learning"
  sidebar:
    style: "docked"
    search: true
    contents:
      - text: "Welcome"
        href: index.qmd
      - section: "Introduction to ML"
        contents:
          - eda.qmd
      - section: "Classification"
        href: metrics.qmd
        contents:
          - categorical_encoding.qmd
          - categorical_pipeline.qmd
      - section: "Natural Language Processing (NLP)"
        contents:
          - ml_text.qmd
          - bagofwords.qmd
          - tfidf.qmd
          - text_classification.qmd
          - LAB2.qmd


 
format:
  html:
    theme: cosmo
    toc: true
    code-fold: true
    fig-align: center
    df-print: paged